name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build ./...
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build ./...
        CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build ./...

    - name: Test
      run: go test -v ./...

    - name: Run Cov
      run: go test -race -coverprofile=coverage.txt -covermode=atomic

    - name: Upload Cov
      run: bash <(curl -s https://codecov.io/bash)
